name: Run hardhat tests
on:
  push:
    branches: ["master"]
  pull_request:
defaults:
  run:
    working-directory: contracts
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: contracts/package-lock.json
      - run: npm i
      - name: hh
        run: npm run test
        env:
          CI: true
